### ISSUE TITLE
Fonts in figures 3 and 4

### ISSUE THREAD

**Issue by cavaglia** [PhoenixBirdCreations/IPAM2021_ML#17]
The fonts of figures 3 and 4 seem to be different than fig 1-2 and 5-6.

**Comment by miqmiq** [comment]
I think the font is the same, but the size of the plots is much smaller. I'll fix that. Also, I think I'm changing the y-labels from "probability" to P_J(I | A_X ), and P(HasNS), P(HasRem) to P(HasNS | A_X), P(HasRem | A_X ) in order to be consistent with the notation from section III.A.
