### ISSUE TITLE
Hyperparameter paragraph

### ISSUE THREAD

**Issue by cavaglia** [PhoenixBirdCreations/IPAM2021_ML#21]
The paragraph starting at line 359 needs to be moved elsewhere since these are not results. A possibility would be to rewrite without mentioning data set D and EOS, break into KNN and RF separately and add in sections II-KNN and II-RF where we discuss the algorithms. For example, for KNN:

_We fix the algorithm hyperparameters by cross-validating over the data set and obtain the highest accuracy. Throughout our analysis we use K = 8 neighbors (instead of K = 2n + 1 = 11 used in [47]), the Manhattan metric, the BallTree algorithm and the neighbors are  weighted by the inverse of their distance to the event._

**Comment by PhoenixBirdCreations** [comment]
Done. Moved the hyperaparameters description to KNN and RF .tex files
