### ISSUE TITLE
Optimal number of neighbors

### ISSUE THREAD

**Issue by cavaglia** [PhoenixBirdCreations/IPAM2021_ML#22]
This sentence in KNN-algorithm:

_"Following Ref. [47], we fix the optimal number of neighbors to K ≈ 2n + 1..."_

contradicts what is being said when the hyperparameters are described! (2n+1 vs 8):

_"For KNN, we use K = 8 neighbors 420 (instead of K = 2n + 1 = 11 as in [47])"_

See also issue #21

**Comment by miqmiq** [comment]
I agree with Marina that maybe we could remove the different options for each hyperparameter and just show the ones we are using. I put K ≈ 2n + 1 because 8 is close to 11, but it's true that can lead to confussions.
