### ISSUE TITLE
Affiliation

### ISSUE THREAD

**Issue by dtsenekl** [PhoenixBirdCreations/IPAM2021_ML#28]
My affiliation should be double, both the university of Tuebingen and the university of Valencia. And I should include this in the acknowledgements: 
The research of DT has been supported by the Spanish Agencia Estatal de Investigaci\'on (grant PID2021-125485NB-C21 funded by MCIN/AEI/10.13039/501100011033 and ERDF A way of making Europe and  by the Generalitat Valenciana (Prometeo program for excellent research groups grant CIPROM/2022/49).

**Comment by cavaglia** [comment]
I am revising the acknowledgements and make their wording more consistent. @dtsenekl : The second part of your sentence "and ERDF A way of making Europe and by the Generalitat Valenciana (Prometeo program for excellent research groups grant CIPROM/2022/49)." is not clear. What is "ERDF A way of making Europe" ?

**Comment by dtsenekl** [comment]
I asked what to include and they sent me exactly that, so I copied  
pasted it. I hadn't noticed that part, I will send an email now.

Παραθέτοντας από cavaglia ***@***.***>:

**Comment by dtsenekl** [comment]
The sentence is correct, it is given by the funding agency like that.  
There is only a parenthesis missing after Europe:

DT's research has been supported by the Spanish Agencia Estatal de  
Investigaci\'on (grant PID2021-125485NB-C21 funded by  
MCIN/AEI/10.13039/501100011033 and ERDF A way of making Europe) and   
by the Generalitat Valenciana (Prometeo program for excellent research  
groups grant CIPROM/2022/49).

Cheers,
Dimitra


Παραθέτοντας από cavaglia ***@***.***>:

**Comment by cavaglia** [comment]
well, in your first text there was a missing parenthesis, which makes all the difference  :-)

**Comment by cavaglia** [comment]
what does ERDF stand for, btw?

**Comment by cavaglia** [comment]
Can you all check the acknowledgements? I made some small changes to make them uniform (sometimes we had grant, some time award, etc. Please check whether you're satisfied. Also a few questions:

1.  Is @PhoenixBirdCreations supported or _partially_ supported by PID2020-118236GB-I00?
2.  @miqmiq and @dtsenekl are (_partially_?) supported by the same award, but the first is written as "PID2021-125485NB-C21 funded by MCIN/AEI/10.13039/501100011033 and by the European Union" the second as "PID2021-125485NB-C21 funded by MCIN/AEI/10.13039/501100011033 and ERDF A way
of making Europe" which one do you want me to change? The text should be the same

**Comment by dtsenekl** [comment]
It's European Regional Development Fund. We thank the ERDF called “A  
way of making Europe”.


Παραθέτοντας από cavaglia ***@***.***>:

**Comment by miqmiq** [comment]
My salary comes through the FPU grant, which is individual. The other grants are for our group. Since I've been in the group for longer time, I still have to acknowledge old projects (PGC2018-095984-B-I00). The way Dimitra wrote the acknowledgement looks fine, you (or I) can write the same thing for me.

**Comment by PhoenixBirdCreations** [comment]
I am _partially_ supported by that grant

**Comment by cavaglia** [comment]
I think I fixed everything. I'll close the issue. Please check and, if further changes are required, reopen.

**Comment by dtsenekl** [comment]
I will have my check finished by tomorrow (my) morning.


Παραθέτοντας από cavaglia ***@***.***>:
