### ISSUE TITLE
Minors

### ISSUE THREAD

**Issue by SimoneA96** [PhoenixBirdCreations/IPAM2021_ML#30]
A few irrelevant things:

- Line 60: kilonova (KN) -> it seems to me that KN is never used again in the paper

- Line 116: the LVK defines [...] -> I would say something like "LVK pipeline" or "LVK collaboration"

- Line 261: the meaning of R and S in D_R and D_S is not super clear (not clear to me at least)

- Line 347: should we cite Refs for BHF_BBB2, SLy, MS1_PP ? 

- Line 395: grey -> gray if we submit to American journals. Same in the captions of Fig.1 and Fig.2

- Line 416: "Section (III A)" -> I would remove the parenthesis (maybe in the tex there is an \eqref instead of \ref) 

- Line 300: we mention Gaussian Process Regression, that is mentioned again in Line 426. I would
            consider using the abbreviation GPR in line 426 

- Line 527: "for the third column ($\chi_1=0.0$ and $\chi_2$)" -> I think "columns" should be "rows" and missing value for chi_2

- Comment on captions: the figure in this paper are in pairs. In (Fig.1, Fig.2) and (Fig.3, Fig.4), the captions
            are repeated with small changes in the text (i.e. KNN->RF). In (Fig.5, Fig.6) and (Fig.7, Fig.8) 
            we used a different procedure, we wrote the captions of Fig.5 and Fig.7 and the in the ones
            of Fig.6 and Fig.8 we wrote something like "same as other figure, but with this instead of that".
            I would unify the style of all caption pairs

**Comment by cavaglia** [comment]
Addressed all comments, except:

Line 261: S stands for teSting, R for TRaining. If you have better suggestions, let me know
Captions: recommendation is to repeat full captions even if similar as captions should be self-consistent and with online publications there are no constraints on space. However, I unified them and improved them (I guess). Please check!

Also, note, in the discussion of the parameter sweeps columns --> rows (twice)

I am closing the issue, but please check accuracy and if needed, reopen
