### ISSUE TITLE
Need reference for gstlal

### ISSUE THREAD

**Issue by cavaglia** [PhoenixBirdCreations/IPAM2021_ML#32]
All pipelines but gstlal have a reference. Please send to @cavaglia

**Comment by frenbox** [comment]
@article{Messick:2016aqy,
    author = "Messick, Cody and others",
    title = "{Analysis Framework for the Prompt Discovery of Compact Binary Mergers in Gravitational-wave Data}",
    eprint = "1604.04324",
    archivePrefix = "arXiv",
    primaryClass = "astro-ph.IM",
    doi = "10.1103/PhysRevD.95.042001",
    journal = "Phys. Rev. D",
    volume = "95",
    number = "4",
    pages = "042001",
    year = "2017"
}

@article{Tsukada:2023edh,
    author = "Tsukada, Leo and others",
    title = "{Improved ranking statistics of the GstLAL inspiral search for compact binary coalescences}",
    eprint = "2305.06286",
    archivePrefix = "arXiv",
    primaryClass = "astro-ph.IM",
    month = "5",
    year = "2023"
}

**Comment by cavaglia** [comment]
This are recent special papers, we need the canonical ref as the ref of
pycbc, mbta etc

**Comment by miqmiq** [comment]
I didn't put any reference to GstLAL because I thought it was already mentioned when introducing the data set. Indeed, I would add the citation where GstLAL is mentioned for the first time.

**Comment by dtsenekl** [comment]
In the online user guide these are the references given for GstLAL:
Messick, C., Blackburn, K., Brady, P., et al. 2017, Phys. Rev. D, 95, 042001. [doi:10.1103/PhysRevD.95.042001](https://doi.org/10.1103/PhysRevD.95.042001)
Sachdev, S., Caudill, S., Fong, H., et al. 2019. [arXiv:1901.08580](https://arxiv.org/abs/1901.08580)

**Comment by frenbox** [comment]
I went through Cody's paper... couldn't find an original paper that explains the Online pipeline quite as well as this

**Comment by dtsenekl** [comment]
I couldn't find an original paper, that's why I checked the online user guide and they had that paper and the other one I wrote above.

**Comment by lmagana3** [comment]
Sachdev is already referenced. Skimmed their abstract and I think that was introducing gstlal.  That was a while back though

**Comment by cavaglia** [comment]
Any conclusion to this? Have no time to comb through references. I need an answer please!

**Comment by dtsenekl** [comment]
I would put the two ones from the online user guide and we can also quote the user guide for the pipelines too: https://rtd.igwn.org/projects/userguide/en/v17.1/analysis/searches.html

**Comment by cavaglia** [comment]
@frenbox : do you agree?

**Comment by lmagana3** [comment]
Doing a quick search, it seems the Sachdev is using GSTLAL in low-latency but as for the creation, the paper by Messick et al says, "In this work, we present the GstLAL-based in- spiral pipeline, a gravitational-wave search pipeline based on the GstLAL library [14], and derived from GStreamer [15] and the LIGO Algorithm Library [16]." 
where refs are:
[14] “Gstlal,” https://www.lsc- group.phys.uwm.edu/ daswg/projects/gstlal.html (), accessed: 2015-07-01.
[15] “Gstreamer,” https://gstreamer.freedesktop.org ().
[16] “Lalsuite,” https://www.lsc- group.phys.uwm.edu/ daswg/projects/lalsuite.html, accessed: 2015-07-01.

so I think those are the two include. Sachdev has already been mentioned, I would double check if Messick is already there before adding it or the pdf won't compile.

https://arxiv.org/pdf/1604.04324.pdf

**Comment by lmagana3** [comment]
This is useful in general: https://lscsoft.docs.ligo.org/gstlal/publications.html

**Comment by frenbox** [comment]
Cody's paper along with Surabhi's paper about early warning should be enough reference about the pipeline. Lets just put those two.
