### ISSUE TITLE
Repetitive "and" at Results.B

### ISSUE THREAD

**Issue by PhoenixBirdCreations** [PhoenixBirdCreations/IPAM2021_ML#33]
In line 424, "Probability estimators for KNN and RF and each of the 23 EoS..." sounds weird to me. I propose "Probability estimators for both algorithms considering each of the 23 EoS..." or "Probability estimators for KNN and RF considering each of the 23 EoS..."

**Comment by cavaglia** [comment]
Made more fluent. Check latest pull. If not satisfied, please reopen issue
