### ISSUE TITLE
Analysis of figs 5-6

### ISSUE THREAD

**Issue by PhoenixBirdCreations** [PhoenixBirdCreations/IPAM2021_ML#34]
In lines 442-444 it says that KNN roc curve for bayesian probability gives TPR=0.975 across all pipelines... But different pipelines say different numbers. I would say that the TPR i between 0.950 and 0.975 for all pipelines...

Then lines 451-455, say that RF slopes are steeper and that gives lower FPR with higher TPR. While it is true that FPR is is slightly lower for the threshold points, the TPR is the same or lower than the TPR of KNN at the same threshold values. Also I don't see RF outperforming KNN for hasRem in gstLAL. I would change the two sentences for something like:
The RF ROC curves for HasMS typycally have steeper slopes than for KNN, resulting in lower FPR and similar TPR at a given threshold. In the case of HasREm, RF performs similarly to KNN for GstLAL and worse for the rest of pipelines.

**Comment by cavaglia** [comment]
Agreed, addressed and issue closed. Please check last version in git and if needed reopen. Thanks for the careful check!
