### ISSUE TITLE
some typos and comments

### ISSUE THREAD

**Issue by dtsenekl** [PhoenixBirdCreations/IPAM2021_ML#35]
Introduction:
1) gamma-ray bursts are first mentioned in lines 37-38, shall we introduce their abbreviation there instead of line 58?
2) Lines 92, 93, is it a desire or a necessity?
3) Line 122: schemas -> schemes 

Classification Algorithms:
4) Line 157 and subtitle: random forests -> random forest

Probability:
5) Line 295: correctly (incorrectly) -> for me it is a bit confusing to write it like that, maybe correctly (+) and incorrectly (-) ?
6) Line 296: can be evaluated similarly to Eq. (6) -> is it really Eq. (6) that has not yet been introduced? Or are there some numberings of equations missing?
7) Lines 326, 337, 357 and a couple more: Do we want to say Ref. in front of the reference? If yes it should be consistent throughout the whole paper

Results:
8) Line 399: grey, Figs 1,2: gray -> we should keep one of these
9) Line 439-440: References of the pipelines: We already mention them in the intro, are we going to mention them twice? and if so, shouldn't the references agree?
10) Line 468: GWTC-3 catalog -> the references are for GWTC-2 and GWTC-3 catalogs

-) Line 501 -> label -> labels
-) Line 505-506 not significantly affect -> not affect significantly 

Conclusions:
11) Line 514-515: signals detected by the LIGO, Virgo and KAGRA detectors -> to be detected by the LVK detectors
12) Line 528-529: a MDC -> an MDC
13) Lines 536-537: the GW source is characterized by these properties -> is properties the correct word?
14) Line 545: ROC metrics -> ROC curves
15) Line 557: with RF outperforming KNN for both HasNS and HasRem BUT in the RESULTS it is written that KNN performs better than RF on HasRem for the O2 data set
16) Lines 566 and 589: the same expression is used: less portable across different pipelines
17) Lines 593-594: I don't like the last part of the sentence where LVK is mentioned twice...
18) Line 507: the computational resources required will be improved? maybe better decreased?

**Comment by dtsenekl** [comment]
And one more: In the Results lines 456-466, this paragraph seems to talk about the O2 set, so should it go to the subsection A?

**Comment by cavaglia** [comment]
@dtsenekl : not sure I understand this comment: "Figs 1,2: gray -> we should keep one of these" Please clarify

**Comment by cavaglia** [comment]
@dtsenekl : "GWTC-3 catalog -> the references are for GWTC-2 and GWTC-3 catalogs" catalogs are cumulative, GWTC-3 includes GWTC-2: "The third Gravitational-wave Transient Catalog (GWTC-3) describes signals detected with Advanced LIGO and Advanced Virgo up to the end of their third observing run. Updating the previous GWTC-2.1, we present candidate gravitational waves from compact binary coalescences during the second half of the third observing run (O3b) between 1 November 2019, 15:00 UTC and 27 March 2020, 17:00 UTC."

**Comment by dtsenekl** [comment]
> @dtsenekl : not sure I understand this comment: "Figs 1,2: gray -> we should keep one of these" Please clarify

I meant that in one place it's written grey and in the other gray

**Comment by cavaglia** [comment]
"Line 505-506 not significantly affect -> not affect significantly" rejected. English is correct

**Comment by dtsenekl** [comment]
> @dtsenekl : "GWTC-3 catalog -> the references are for GWTC-2 and GWTC-3 catalogs" catalogs are cumulative, GWTC-3 includes GWTC-2: "The third Gravitational-wave Transient Catalog (GWTC-3) describes signals detected with Advanced LIGO and Advanced Virgo up to the end of their third observing run. Updating the previous GWTC-2.1, we present candidate gravitational waves from compact binary coalescences during the second half of the third observing run (O3b) between 1 November 2019, 15:00 UTC and 27 March 2020, 17:00 UTC."

Yes, I saw that. Sorry, my bad, I got a bit confused with the catalog 2, 3 and data from O2 and O3...

**Comment by cavaglia** [comment]
Everything addressed except:

"Lines 326, 337, 357 and a couple more: Do we want to say Ref. in front of the reference? If yes it should be consistent throughout the whole paper" I think the convention is typically no "Ref" but one needs to say "in Ref. []" or "from Ref. []" and not "in []" and "from []" at least that's what I remember from PRD, but that was a difefrent time and jurnals change all the time. they'll hopefully fix it.

Also not addressed "Line 505-506 not significantly affect -> not affect significantly" rejected. English is correct

Also not addressed the GstLAL reference that will be dealt when the other opened issue  is closed.

Please pull, check and open another issue if anything is still not good. Thanks for the thorough check!

**Comment by dtsenekl** [comment]
Sorry for correcting a couple of no mistakes! I checked again the results and the conclusions and the few changes in the other sections. I haven't found other mistakes. I like the changes in the conclusions.
