### ISSUE TITLE
Some Comments

### ISSUE THREAD

**Issue by frenbox** [PhoenixBirdCreations/IPAM2021_ML#36]
- Line 22, in Abstract,  new way to compute Bayesian probabilities ... of **producing an electromagnetic counterpart**. Should we say possibility of post-merger mass remnant. If we make the current statement, it might be misleading.

- Line 104, **the non-stationarity of detector's power spectral density **. Is this an accurate statement to make?
- Line 116, is the sentence starting with **For example, ... ** necessary?
- Line 136, Line 156, we are using the word **alternative algorithms**. RF definitely qualifies for that but KNN? Are we saying this because we tweaked the way we label and train?
- Line 231 can P values be written as a "subset". I may be stupid at the same time. Just curious?

**Comment by cavaglia** [comment]
Addressed all comments. Abstract has been quite revised (didn't have time to do it yesterday) please check whether comments have been addressed to your satisfaction. If not, reopen issue.
