### ISSUE TITLE
Addressing Tom's comments

### ISSUE THREAD

**Issue by miqmiq** [PhoenixBirdCreations/IPAM2021_ML#39]
Line 22: maybe "more accurately" is too strong. We could say "we are able to improve the prediction of..." and maybe add that we prove this for O2 data and exclusively from GstLAL. 

Line 446: remove this? We do not want to blame the pipelines and here we are doing so, even though it has been proven that SPIIR does not perform that well on O3 MDC data. We could stress (at the discussion) that the poor performance of RF on O3 MDC events is not pipelines' fault, it is because we lack of training data from those pipelines. And also change wording to avoid making too strong statements. 

To avoid misunderstandings, Sushant suggested to add an schematic figure where we compare the current LVK implementation and our Bayesian approach. That could be located in section III.A.

**Comment by PhoenixBirdCreations** [comment]
Fixed comments 1-4  in the doc with Marco's suggestions. I think that solves this issue, except if you want to include that figure. Reopen if needed.
